CREATE TABLE mahasiswa (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    nama TEXT NOT NULL,
    nim TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    jurusan TEXT NOT NULL,
    fakultas TEXT NOT NULL,
    is_active BOOLEAN DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);
